language: python
python:
  - 3.6
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 6
  - pip install cookiecutter
install:
  - pushd $(mktemp -d)
  - cookiecutter $TRAVIS_BUILD_DIR --config-file $TRAVIS_BUILD_DIR/tests/testconfig.yaml --no-input
  - pushd jupyter-widget-testwidgets
  - pip install --upgrade -v -e ".[test]"
before_script:
  - |
    export CHROME_BIN=chromium-browser
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
script:
  - py.test
  - npm test
  - pip uninstall -y ipywidgettestwidgets
  - pip install .
  - jupyter nbextension enable --py --sys-prefix ipywidgettestwidgets
  - pip install jupyterlab
  - jupyter labextension list
  - jupyter labextension list 2>&1 | grep -q jupyter-widget-testwidgets
  - jupyter labextension link
  - popd
  - popd
